require 'vendor/mvc/scripts/builder'
require 'vendor/mvc/scripts/builders/plugin_builder'
require 'vendor/mvc/scripts/builders/mvc_builder'
require 'vendor/mvc/scripts/builders/app_builder'
require 'vendor/mvc/scripts/builders/css_builder'
require 'vendor/mvc/scripts/builders/all_builder'
require 'vendor/mvc/scripts/builders/docs_builder'

require 'vendor/mvc/scripts/generator'
require 'vendor/mvc/scripts/plugin'
require 'vendor/mvc/scripts/settings'
require 'vendor/mvc/scripts/setup'
require 'vendor/mvc/scripts/stats'
require 'vendor/mvc/scripts/test'
require 'vendor/mvc/scripts/update'