require 'vendor/mvc/scripts/builder'
require 'vendor/mvc/scripts/generator'
require 'vendor/mvc/scripts/plugin'
require 'vendor/mvc/scripts/settings'
require 'vendor/mvc/scripts/setup'
require 'vendor/mvc/scripts/stats'
require 'vendor/mvc/scripts/update'